CREATE TABLE PRODUTO (
  NSERIE             varchar(255) NOT NULL, 
  REVISAO            varchar(30), 
  DATA_PROD          date NOT NULL, 
  REFUGO             int4, 
  MOTIVO_REFUGO      varchar(255), 
  ETAPA              varchar(255) NOT NULL, 
  STATUS             int4 NOT NULL, 
  QTD_TESTE_ELE      int4, 
  MODELO_FK          int8 NOT NULL, 
  LOTE_FK            varchar(255) NOT NULL, 
  INTEGRACAO_FIN_FK  int8, 
  INSPECAO_FINAL_FK  int8, 
  INSPECAO_FINAL_FK2 int8
);


CREATE TABLE USUARIO (
  ID     int8 NOT NULL, 
  LOGIN  varchar(40) NOT NULL UNIQUE, 
  EMAIL  varchar(50), 
  NOME   varchar(70) NOT NULL, 
  SENHA  varchar(30) NOT NULL, 
  PERFIL int4 NOT NULL
);


CREATE TABLE MODELO (
  ID       int8 NOT NULL, 
  MODELO   varchar(50) NOT NULL UNIQUE, 
  DESCICAO varchar(255), 
  IT       varchar(255), 
  TIPO     varchar(20) NOT NULL
);


CREATE TABLE LOTE (
  ID             varchar(255) NOT NULL, 
  DATA_CRIACAO   date, 
  NSERIE_INICIAL int8, 
  NSERIE_FINAL   int4, 
  QTD            int4, 
  QTDE_ATUAL     int4, 
  DATA_PROD      date
);


CREATE TABLE PEM (
  NSERIE             varchar(255) NOT NULL, 
  REFUGO             int4, 
  MOTIVO_REFUGO      varchar(255), 
  ETAPA              varchar(50) NOT NULL, 
  STATUS             int4 NOT NULL, 
  QTD_TESTE_ELE      int4, 
  PRODUTO_FK         varchar(255), 
  MODELO_FK          int8 NOT NULL, 
  INSPECAO_VISUAL_FK int8, 
  INSPECAO_FINAL_FK  int8
);


CREATE TABLE RETRABALHO (
  ID          int8 NOT NULL, 
  ORIGEM      varchar(255), 
  DATA_INICIO date, 
  DATA_FIM    date, 
  REFUGOU     int4, 
  USUARIO_FK  int8 NOT NULL, 
  PRODUTO_FK  varchar(255), 
  PEM_FK      varchar(255)
);


CREATE TABLE INTEGRACAO_FINAL (
  ID             int8 NOT NULL, 
  DATA_INICIO    date NOT NULL, 
  DATA_FIM       date NOT NULL, 
  QTD_REPROCESSO int4, 
  USUARIO_FK     int8 NOT NULL
);


CREATE TABLE INSPECAO_VISUAL (
  ID             int8 NOT NULL, 
  DATA_INICIO    date, 
  DATA_FIM       int4, 
  USUARIO_FK     int8 NOT NULL, 
  QTD_REPROCESSO int4
);


CREATE TABLE INSPECAO_FINAL (
  ID             int8 NOT NULL, 
  DATA_INICIO    int4, 
  DATA_FIM       date, 
  QTD_REPROCESSO int4, 
  USUARIO_FK     int8 NOT NULL
);

CREATE TABLE TESTE_ELETRICO (
  ID          int8 NOT NULL, 
  DATA_INICIO date, 
  DATA_FIM    date, 
  VOLTAGEM    varchar(50), 
  USUARIO_FK  int8 NOT NULL, 
  PRODUTO_FK  varchar(255) NOT NULL, 
  PEM_FK      varchar(255) NOT NULL
);


CREATE TABLE PROGRAMACAO (
  ID               int8 NOT NULL, 
  DATA_PROG_INICIO date, 
  DATA_PROG_FIM    date, 
  DATA_REAL_INICIO date, 
  DATA_REAL_FIM    int4, 
  OBSERVACOES      varchar(255), 
  TIPO_PROD        varchar(50), 
  LOTE_FK          varchar(255) NOT NULL
);


CREATE TABLE EQUIP_MEDICAO (
  PATRIMONIO      varchar(255) NOT NULL, 
  MARCA           varchar(100), 
  MODELO          varchar(255), 
  SETOR           varchar(255), 
  DATA_VENC_CALIB date, 
  STATUS          varchar(100)
);


CREATE TABLE EQUIP_MEDICAO_TESTE_ELETRICO_1 (
  EQUIP_MEDICAOPATRIMONIO varchar(255) NOT NULL, 
  TESTE_ELETRICO_FK       int8 NOT NULL
);


CREATE TABLE CLASSE_DEFEITOS (
  CODIGO     BIGSERIAL NOT NULL, 
  DESCRICAO varchar(255) NOT NULL, 
  TIPO      varchar(20)
);


CREATE TABLE DEFEITO (
  ID                 BIGSERIAL NOT NULL, 
  LOC1              varchar(10), 
  LOC2              varchar(10), 
  LOC3              varchar(10), 
  LOC4              varchar(10), 
  LOC5              varchar(10), 
  CLASSE_DEFEITO_FK int8 NOT NULL, 
  REPARO_FK         int8 NOT NULL
);


ALTER TABLE PRODUTO ADD PRIMARY KEY (NSERIE);
ALTER TABLE USUARIO ADD PRIMARY KEY (ID);
ALTER TABLE MODELO ADD PRIMARY KEY (ID);
ALTER TABLE LOTE ADD PRIMARY KEY (ID);
ALTER TABLE PEM ADD PRIMARY KEY (NSERIE);
ALTER TABLE RETRABALHO ADD PRIMARY KEY (ID);
ALTER TABLE INTEGRACAO_FINAL ADD PRIMARY KEY (ID);
ALTER TABLE INSPECAO_VISUAL ADD PRIMARY KEY (ID);
ALTER TABLE INSPECAO_FINAL ADD PRIMARY KEY (ID);
ALTER TABLE TESTE_ELETRICO ADD PRIMARY KEY (ID);
ALTER TABLE PROGRAMACAO ADD PRIMARY KEY (ID);
ALTER TABLE EQUIP_MEDICAO ADD PRIMARY KEY (PATRIMONIO);
ALTER TABLE EQUIP_MEDICAO_TESTE_ELETRICO_1 ADD PRIMARY KEY (EQUIP_MEDICAOPATRIMONIO, TESTE_ELETRICO_FK);
ALTER TABLE CLASSE_DEFEITOS ADD PRIMARY KEY (CODIGO);
ALTER TABLE DEFEITO ADD PRIMARY KEY (ID);


ALTER TABLE PRODUTO ADD CONSTRAINT FKPRODUTO182310 FOREIGN KEY (MODELO_FK) REFERENCES MODELO (ID);
ALTER TABLE PEM ADD CONSTRAINT FKPEM167025 FOREIGN KEY (PRODUTO_FK) REFERENCES PRODUTO (NSERIE);
ALTER TABLE PRODUTO ADD CONSTRAINT FKPRODUTO86499 FOREIGN KEY (LOTE_FK) REFERENCES LOTE (ID);
ALTER TABLE RETRABALHO ADD CONSTRAINT FKRETRABALHO525509 FOREIGN KEY (USUARIO_FK) REFERENCES USUARIO (ID);
ALTER TABLE PRODUTO ADD CONSTRAINT FKPRODUTO228453 FOREIGN KEY (INTEGRACAO_FIN_FK) REFERENCES INTEGRACAO_FINAL (ID);
ALTER TABLE INTEGRACAO_FINAL ADD CONSTRAINT FKINTEGRACAO873375 FOREIGN KEY (USUARIO_FK) REFERENCES USUARIO (ID);
ALTER TABLE INSPECAO_VISUAL ADD CONSTRAINT FKINSPECAO_V397622 FOREIGN KEY (USUARIO_FK) REFERENCES USUARIO (ID);
ALTER TABLE PRODUTO ADD CONSTRAINT FKPRODUTO234866 FOREIGN KEY (INSPECAO_FINAL_FK) REFERENCES INSPECAO_VISUAL (ID);
ALTER TABLE PRODUTO ADD CONSTRAINT FKPRODUTO756987 FOREIGN KEY (INSPECAO_FINAL_FK2) REFERENCES INSPECAO_FINAL (ID);
ALTER TABLE INSPECAO_FINAL ADD CONSTRAINT FKINSPECAO_F116415 FOREIGN KEY (USUARIO_FK) REFERENCES USUARIO (ID);
ALTER TABLE TESTE_ELETRICO ADD CONSTRAINT FKTESTE_ELET26040 FOREIGN KEY (USUARIO_FK) REFERENCES USUARIO (ID);
ALTER TABLE PROGRAMACAO ADD CONSTRAINT FKPROGRAMACA483333 FOREIGN KEY (LOTE_FK) REFERENCES LOTE (ID);
ALTER TABLE EQUIP_MEDICAO_TESTE_ELETRICO_1 ADD CONSTRAINT FKEQUIP_MEDI893426 FOREIGN KEY (EQUIP_MEDICAOPATRIMONIO) REFERENCES EQUIP_MEDICAO (PATRIMONIO);
ALTER TABLE EQUIP_MEDICAO_TESTE_ELETRICO_1 ADD CONSTRAINT FKEQUIP_MEDI582970 FOREIGN KEY (TESTE_ELETRICO_FK) REFERENCES TESTE_ELETRICO (ID);
ALTER TABLE PEM ADD CONSTRAINT FKPEM612767 FOREIGN KEY (MODELO_FK) REFERENCES MODELO (ID);
ALTER TABLE PEM ADD CONSTRAINT FKPEM466125 FOREIGN KEY (INSPECAO_VISUAL_FK) REFERENCES INSPECAO_VISUAL (ID);
ALTER TABLE PEM ADD CONSTRAINT FKPEM85616 FOREIGN KEY (INSPECAO_FINAL_FK) REFERENCES INSPECAO_FINAL (ID);
ALTER TABLE TESTE_ELETRICO ADD CONSTRAINT FKTESTE_ELET108403 FOREIGN KEY (PRODUTO_FK) REFERENCES PRODUTO (NSERIE);
ALTER TABLE TESTE_ELETRICO ADD CONSTRAINT FKTESTE_ELET778948 FOREIGN KEY (PEM_FK) REFERENCES PEM (NSERIE);
ALTER TABLE RETRABALHO ADD CONSTRAINT FKRETRABALHO528444 FOREIGN KEY (PRODUTO_FK) REFERENCES PRODUTO (NSERIE);
ALTER TABLE RETRABALHO ADD CONSTRAINT FKRETRABALHO198990 FOREIGN KEY (PEM_FK) REFERENCES PEM (NSERIE);
ALTER TABLE DEFEITO ADD CONSTRAINT FKDEFEITO664503 FOREIGN KEY (CLASSE_DEFEITO_FK) REFERENCES CLASSE_DEFEITOS (CODIGO);
ALTER TABLE DEFEITO ADD CONSTRAINT FKDEFEITO347635 FOREIGN KEY (REPARO_FK) REFERENCES RETRABALHO (ID);


CREATE UNIQUE INDEX PRODUTO_NSERIE 
  ON PRODUTO (NSERIE);
CREATE UNIQUE INDEX USUARIO_ID 
  ON USUARIO (ID);
CREATE INDEX MODELO_ID 
  ON MODELO (ID);
CREATE INDEX LOTE_ID 
  ON LOTE (ID);
CREATE UNIQUE INDEX PEM_NSERIE 
  ON PEM (NSERIE);
CREATE UNIQUE INDEX RETRABALHO_ID 
  ON RETRABALHO (ID);
CREATE UNIQUE INDEX INTEGRACAO_FINAL_ID 
  ON INTEGRACAO_FINAL (ID);
CREATE UNIQUE INDEX INSPECAO_VISUAL_ID 
  ON INSPECAO_VISUAL (ID);
CREATE INDEX INSPECAO_FINAL_ID 
  ON INSPECAO_FINAL (ID);
CREATE UNIQUE INDEX TESTE_ELETRICO_ID 
  ON TESTE_ELETRICO (ID);
CREATE UNIQUE INDEX PROGRAMACAO_ID 
  ON PROGRAMACAO (ID);
CREATE UNIQUE INDEX EQUIP_MEDICAO_PATRIMONIO 
  ON EQUIP_MEDICAO (PATRIMONIO);
CREATE UNIQUE INDEX CLASSE_DEFEITOS_CODIGO 
  ON CLASSE_DEFEITOS (CODIGO);
  
  
CREATE SEQUENCE seq_USUARIO;
CREATE SEQUENCE seq_MODELO;
CREATE SEQUENCE seq_RETRABALHO;
CREATE SEQUENCE seq_INTEGRACAO_FINAL;
CREATE SEQUENCE seq_INSPECAO_VISUAL;
CREATE SEQUENCE seq_INSPECAO_FINAL;
CREATE SEQUENCE seq_TESTE_ELETRICO;
CREATE SEQUENCE seq_PROGRAMACAO;


