CREATE TABLE PRODUTO (
  NSERIE             varchar(255) NOT NULL PRIMARY KEY, 
  REVISAO            varchar(30), 
  DATA_PROD          date NOT NULL, 
  REFUGO             int(10), 
  MOTIVO_REFUGO      varchar(255), 
  ETAPA              varchar(255) NOT NULL, 
  STATUS             int(10) NOT NULL, 
  QTD_TESTE_ELE      int(11), 
  MODELO_FK          bigint(19) NOT NULL, 
  LOTE_FK            varchar(255) NOT NULL, 
  INTEGRACAO_FIN_FK  bigint(19), 
  INSPECAO_FINAL_FK  bigint(19), 
  INSPECAO_FINAL_FK2 bigint(19), 
  UNIQUE INDEX (NSERIE)) ;
  
  
CREATE TABLE USUARIO (
  ID     bigint(19) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  LOGIN  varchar(40) NOT NULL UNIQUE, 
  EMAIL  varchar(50), 
  NOME   varchar(70) NOT NULL, 
  SENHA  varchar(30) NOT NULL, 
  PERFIL int(10) NOT NULL, 
  PRIMARY KEY (ID), 
  UNIQUE INDEX (ID)) ;
  
  
CREATE TABLE MODELO (
  ID       bigint(19) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  MODELO   varchar(50) NOT NULL UNIQUE, 
  DESCICAO varchar(255), 
  IT       varchar(255), 
  TIPO     varchar(20) NOT NULL, 
  PRIMARY KEY (ID), 
  UNIQUE INDEX (ID)) ;
  
  
CREATE TABLE LOTE (
  ID             varchar(255) NOT NULL PRIMARY KEY, 
  DATA_CRIACAO   date, 
  NSERIE_INICIAL bigint(19), 
  NSERIE_FINAL   int(10), 
  QTD            int(10), 
  QTDE_ATUAL     int(10), 
  DATA_PROD      date, 
  INDEX (ID)) ;
  
  
CREATE TABLE PEM (
  NSERIE             varchar(255) NOT NULL PRIMARY KEY, 
  REFUGO             int(10), 
  MOTIVO_REFUGO      varchar(255), 
  ETAPA              varchar(50) NOT NULL, 
  STATUS             int(10) NOT NULL, 
  QTD_TESTE_ELE      int(11), 
  PRODUTO_FK         varchar(255), 
  MODELO_FK          bigint(19) NOT NULL, 
  INSPECAO_VISUAL_FK bigint(19), 
  INSPECAO_FINAL_FK  bigint(19), 
  UNIQUE INDEX (NSERIE)) ;
  
  
CREATE TABLE RETRABALHO (
  ID          bigint(19) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  ORIGEM      varchar(255), 
  DATA_INICIO date, 
  DATA_FIM    date, 
  REFUGOU     int(10), 
  USUARIO_FK  bigint(19) NOT NULL, 
  PRODUTO_FK  varchar(255), 
  PEM_FK      varchar(255), 
  PRIMARY KEY (ID), 
  UNIQUE INDEX (ID)) ;
  
  
CREATE TABLE INTEGRACAO_FINAL (
  ID             bigint(19) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  DATA_INICIO    date NOT NULL, 
  DATA_FIM       date NOT NULL, 
  QTD_REPROCESSO int(11), 
  USUARIO_FK     bigint(19) NOT NULL, 
  PRIMARY KEY (ID), 
  UNIQUE INDEX (ID)) ;
  
  
CREATE TABLE INSPECAO_VISUAL (
  ID             bigint(19) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  DATA_INICIO    date, 
  DATA_FIM       int(10), 
  USUARIO_FK     bigint(19) NOT NULL, 
  QTD_REPROCESSO int(11), 
  PRIMARY KEY (ID), 
  UNIQUE INDEX (ID)) ;
  
  
CREATE TABLE INSPECAO_FINAL (
  ID             bigint(19) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  DATA_INICIO    int(10), 
  DATA_FIM       date, 
  QTD_REPROCESSO int(11), 
  USUARIO_FK     bigint(19) NOT NULL, 
  PRIMARY KEY (ID), 
  UNIQUE INDEX (ID)) ;
  
  
CREATE TABLE TESTE_ELETRICO (
  ID          bigint(19) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  DATA_INICIO date, 
  DATA_FIM    date, 
  VOLTAGEM    varchar(50), 
  USUARIO_FK  bigint(19) NOT NULL, 
  PRODUTO_FK  varchar(255) NOT NULL, 
  PEM_FK      varchar(255) NOT NULL, 
  PRIMARY KEY (ID), 
  UNIQUE INDEX (ID)) ;
  
  
CREATE TABLE PROGRAMACAO (
  ID               bigint(19) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  DATA_PROG_INICIO date, 
  DATA_PROG_FIM    date, 
  DATA_REAL_INICIO date, 
  DATA_REAL_FIM    int(10), 
  OBSERVACOES      varchar(255), 
  TIPO_PROD        varchar(50), 
  LOTE_FK          varchar(255) NOT NULL, 
  PRIMARY KEY (ID), 
  UNIQUE INDEX (ID)) ;
  
  
CREATE TABLE EQUIP_MEDICAO (
  PATRIMONIO      varchar(255) NOT NULL PRIMARY KEY, 
  MARCA           varchar(100), 
  MODELO          varchar(255), 
  SETOR           varchar(255), 
  DATA_VENC_CALIB date, 
  STATUS          varchar(100), 
  UNIQUE INDEX (PATRIMONIO)) ;
  
  
CREATE TABLE EQUIP_MEDICAO_TESTE_ELETRICO (
  EQUIP_MEDICAOPATRIMONIO varchar(255) NOT NULL, 
  TESTE_ELETRICO_FK       bigint(19) NOT NULL) ;
  
  
CREATE TABLE CLASSE_DEFEITOS (
  CODIGO    bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  DESCRICAO varchar(255) NOT NULL, 
  TIPO      varchar(20), 
  PRIMARY KEY (CODIGO), 
  UNIQUE INDEX (CODIGO)) ;
  
  
CREATE TABLE DEFEITO (
  ID                bigint(19) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  LOC1              varchar(10), 
  LOC2              varchar(10), 
  LOC3              varchar(10), 
  LOC4              varchar(10), 
  LOC5              varchar(10), 
  CLASSE_DEFEITO_FK bigint(20) NOT NULL, 
  REPARO_FK         bigint(19) NOT NULL, 
  PRIMARY KEY (ID), 
  UNIQUE INDEX (ID)) ;



ALTER TABLE PRODUTO ADD INDEX FKPRODUTO182310 (MODELO_FK), ADD CONSTRAINT FKPRODUTO182310 FOREIGN KEY (MODELO_FK) REFERENCES MODELO (ID);
ALTER TABLE PEM ADD INDEX FKPEM167025 (PRODUTO_FK), ADD CONSTRAINT FKPEM167025 FOREIGN KEY (PRODUTO_FK) REFERENCES PRODUTO (NSERIE);
ALTER TABLE PRODUTO ADD INDEX FKPRODUTO86499 (LOTE_FK), ADD CONSTRAINT FKPRODUTO86499 FOREIGN KEY (LOTE_FK) REFERENCES LOTE (ID);
ALTER TABLE RETRABALHO ADD INDEX FKRETRABALHO525509 (USUARIO_FK), ADD CONSTRAINT FKRETRABALHO525509 FOREIGN KEY (USUARIO_FK) REFERENCES USUARIO (ID);
ALTER TABLE PRODUTO ADD INDEX FKPRODUTO228453 (INTEGRACAO_FIN_FK), ADD CONSTRAINT FKPRODUTO228453 FOREIGN KEY (INTEGRACAO_FIN_FK) REFERENCES INTEGRACAO_FINAL (ID);
ALTER TABLE INTEGRACAO_FINAL ADD INDEX FKINTEGRACAO873375 (USUARIO_FK), ADD CONSTRAINT FKINTEGRACAO873375 FOREIGN KEY (USUARIO_FK) REFERENCES USUARIO (ID);
ALTER TABLE INSPECAO_VISUAL ADD INDEX FKINSPECAO_V397622 (USUARIO_FK), ADD CONSTRAINT FKINSPECAO_V397622 FOREIGN KEY (USUARIO_FK) REFERENCES USUARIO (ID);
ALTER TABLE PRODUTO ADD INDEX FKPRODUTO234866 (INSPECAO_FINAL_FK), ADD CONSTRAINT FKPRODUTO234866 FOREIGN KEY (INSPECAO_FINAL_FK) REFERENCES INSPECAO_VISUAL (ID);
ALTER TABLE PRODUTO ADD INDEX FKPRODUTO756987 (INSPECAO_FINAL_FK2), ADD CONSTRAINT FKPRODUTO756987 FOREIGN KEY (INSPECAO_FINAL_FK2) REFERENCES INSPECAO_FINAL (ID);
ALTER TABLE INSPECAO_FINAL ADD INDEX FKINSPECAO_F116415 (USUARIO_FK), ADD CONSTRAINT FKINSPECAO_F116415 FOREIGN KEY (USUARIO_FK) REFERENCES USUARIO (ID);
ALTER TABLE TESTE_ELETRICO ADD INDEX FKTESTE_ELET26040 (USUARIO_FK), ADD CONSTRAINT FKTESTE_ELET26040 FOREIGN KEY (USUARIO_FK) REFERENCES USUARIO (ID);
ALTER TABLE PROGRAMACAO ADD INDEX FKPROGRAMACA483333 (LOTE_FK), ADD CONSTRAINT FKPROGRAMACA483333 FOREIGN KEY (LOTE_FK) REFERENCES LOTE (ID);
ALTER TABLE EQUIP_MEDICAO_TESTE_ELETRICO_1 ADD INDEX FKEQUIP_MEDI893426 (EQUIP_MEDICAOPATRIMONIO), ADD CONSTRAINT FKEQUIP_MEDI893426 FOREIGN KEY (EQUIP_MEDICAOPATRIMONIO) REFERENCES EQUIP_MEDICAO (PATRIMONIO);
ALTER TABLE EQUIP_MEDICAO_TESTE_ELETRICO_1 ADD INDEX FKEQUIP_MEDI582970 (TESTE_ELETRICO_FK), ADD CONSTRAINT FKEQUIP_MEDI582970 FOREIGN KEY (TESTE_ELETRICO_FK) REFERENCES TESTE_ELETRICO (ID);
ALTER TABLE PEM ADD INDEX FKPEM612767 (MODELO_FK), ADD CONSTRAINT FKPEM612767 FOREIGN KEY (MODELO_FK) REFERENCES MODELO (ID);
ALTER TABLE PEM ADD INDEX FKPEM466125 (INSPECAO_VISUAL_FK), ADD CONSTRAINT FKPEM466125 FOREIGN KEY (INSPECAO_VISUAL_FK) REFERENCES INSPECAO_VISUAL (ID);
ALTER TABLE PEM ADD INDEX FKPEM85616 (INSPECAO_FINAL_FK), ADD CONSTRAINT FKPEM85616 FOREIGN KEY (INSPECAO_FINAL_FK) REFERENCES INSPECAO_FINAL (ID);
ALTER TABLE TESTE_ELETRICO ADD INDEX FKTESTE_ELET108403 (PRODUTO_FK), ADD CONSTRAINT FKTESTE_ELET108403 FOREIGN KEY (PRODUTO_FK) REFERENCES PRODUTO (NSERIE);
ALTER TABLE TESTE_ELETRICO ADD INDEX FKTESTE_ELET778948 (PEM_FK), ADD CONSTRAINT FKTESTE_ELET778948 FOREIGN KEY (PEM_FK) REFERENCES PEM (NSERIE);
ALTER TABLE RETRABALHO ADD INDEX FKRETRABALHO528444 (PRODUTO_FK), ADD CONSTRAINT FKRETRABALHO528444 FOREIGN KEY (PRODUTO_FK) REFERENCES PRODUTO (NSERIE);
ALTER TABLE RETRABALHO ADD INDEX FKRETRABALHO198990 (PEM_FK), ADD CONSTRAINT FKRETRABALHO198990 FOREIGN KEY (PEM_FK) REFERENCES PEM (NSERIE);
ALTER TABLE DEFEITO ADD INDEX FKDEFEITO664503 (CLASSE_DEFEITO_FK), ADD CONSTRAINT FKDEFEITO664503 FOREIGN KEY (CLASSE_DEFEITO_FK) REFERENCES CLASSE_DEFEITOS (CODIGO);
ALTER TABLE DEFEITO ADD INDEX FKDEFEITO347635 (REPARO_FK), ADD CONSTRAINT FKDEFEITO347635 FOREIGN KEY (REPARO_FK) REFERENCES RETRABALHO (ID);
