INSERT INTO PEM
  (NSERIE, REFUGO, MOTIVO_REFUGO, ETAPA, STATUS, QTD_TESTE_ELE, PRODUTO_FK, MODELO_FK, INSPECAO_VISUAL_FK, INSPECAO_FINAL_FK) 
VALUES 
  ('1', null, null, null, null, null, null, null, null, null);
